//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space_Buns_Ordering_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string invoiceID { get; set; }
        public string paymentID { get; set; }
        public string remarks { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
