//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space_Buns_Ordering_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string orderID { get; set; }
        public string productID { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> discount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
