//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space_Buns_Ordering_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string reservationID { get; set; }
        public string customerID { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string venue { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
